eureka:
  instance:
    ip-address: true

  client:
    register-with-eureka: false
    fetch-registry: false
    servicesurl: http://${eureka.instance.hostname}:${server.port}/eureka/

server:
  port: 8090