spring:
  application:
    name: service-saludar

eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:8090/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.appication.instance_id:${random.value}}

server:
  port: 0